### ISSUE TITLE
Wrong spacegroup

### ISSUE THREAD

**Issue by shyuep** [atztogo/spglib#14]
I installed spglib 1.9.4.2 via pip on Mac OSX El Capitan.

The following code results in a wrong spacegroup:

```python
In [22]: print m
[[ -1.23500000e+00  -1.23500000e+00   0.00000000e+00]
 [ -2.13908275e+00   2.13908275e+00   0.00000000e+00]
 [ -3.02487759e-16   1.51243880e-16  -6.80000000e+00]]

In [23]: print pos
[[ 0.6667  0.3333  0.75  ]
 [ 0.3333  0.6667  0.25  ]
 [ 0.      0.      0.75  ]
 [ 0.      0.      0.25  ]]

In [24]: print numbers
[6, 6, 6, 6]

In [25]: spglib.get_symmetry_dataset((m, pos, numbers))["international"]
Out[25]: u'P2_1/m'
```

This is a standard graphite unit cell.

**Comment by atztogo** [comment]
Could you try spglib.get_symmetry_dataset((np.transpose(m), pos, numbers), symprec=1e-3)["international"]?

**Comment by shyuep** [comment]
That works. seems like spglib changed the definition of the lattice vector to the transpose in 1.9+?

**Comment by atztogo** [comment]
Yes, unfortunately. The matrix for lattice parameters is transposed in spglib.py, so the matrix for _spglib.c is unchanged.

**Comment by shyuep** [comment]
BTW, is the magnetic spacegroup implemented in the python API? As far as I can tell, passing in magmoms doesn't seem to change the symmetry.

**Comment by atztogo** [comment]
Magnetic space group type determination is not implemented. I don't have the data set to be compared and I don't understand the algorithm to do it. What you can get is a set of symmetry operations considering collinear magnetic moments for which I've not written the document well.
