### ISSUE TITLE
Segfault in get_symmetry

### ISSUE THREAD

**Issue by shyuep** [atztogo/spglib#15]
The following gives a segfault on spglib 1.9.4.2 on MacOS.

```python
import spglib
cell = ([[ 3.84019793,  0, 0], [1.92009897, 3.32571019,  0], [ 0, -2.21713849, 3.13550906]], 
           [[ 0.  ,  0.  ,  0.  ], [ 0.75,  0.75,  0.75], [ 0.5 ,  0.5 ,  0.5 ], [ 0.25,  0.25,  0.25]], 
           [1, 1, 1, 2], [0, 0, 0, 0])
spglib.get_symmetry(cell, 0.1, 5)
```

If the angle tolerance is not set, it works fine.

**Comment by shyuep** [comment]
Sorry, I think this is just an issue with specifying the wrong params. Seems like get_symmetry has a use_magmom option. I have used explicit kwargs to make sure this doesn't happen in future.

**Comment by atztogo** [comment]
But I see the design of this method is very bad both of input and output in the case with magnetic moments. Please allow me to change the interface a bit in the future release.
