### ISSUE TITLE
pip install failure in 'clean' virtualenv

### ISSUE THREAD

**Issue by glaweh** [atztogo/spglib#16]
Hi,
a clean virtualenv does not contain numpy, while spglib's setup.py depends on it being installed. could you provide a setup_requires in the pypi-package, such that numpy would be automatically pulled before spglib's setup.py tries to compile the extension

regards,
Henning

**Comment by atztogo** [comment]
I don't have experience to use virtualenv. In addition, I need jochym's help on pypi-packaging. So let me think how I can proceed.

I googled about 'setup_requires'. It seems this is a part of setuptools. So I see there are three players, virtualenv, pip, and setuptools, but I've not understood how they work mutually. Am I correct that what you expect is just adding a 'setup_requires' keyword in setup.py with replacing distutils to setuptools? Or do I need to prepare another setting file for pip?

**Comment by glaweh** [comment]
I am also by way no expert in python packaging, so I think that jochym may be the one able to solve this.
setup_requires, as far as I understand it, needs to end up in the pypi metadata, so easy_install and pip will install numpy before trying to run spglib/setup.py

**Comment by blokhin** [comment]
Note, that numpy employs its own very slow implementations, if the low-level numerical libraries aren't properly linked. This can be the case, if numpy is automatically installed. So pre-installed numpy is always the better choice. You may use "--system-site-packages" key to access it from virtualenv.

**Comment by jochym** [comment]
I believe we have a problem with the pypi package. The conda install works fine, while the pypi package installs fine but cannot be imported if there is no numpy installed. @atztogo the setup as it it now requires numpy to be present. Furthermore setuptools are preferred over distutils according to upstream docs. I think we should make the switch. Shell I prepare it or you prefer to make the change yourself?

**Comment by atztogo** [comment]
As @jochym wrote, we should use setuptools when making the pypi package. I will modify setup.py to use setuptools if the setuptools exists in the system. On travis-CI, I need to ask @jochym's help. I think virtualenv test in travis CI is not very necessary.

@blokhin's comment is what beyond my knowledge. But I think it implies there are different situations where spglib can be used.

**Comment by atztogo** [comment]
To @glaweh. In spglib 1.9.5, install_requires=['numpy'] is added to setup.py. Does this satisfy your request?

**Comment by shyuep** [comment]
I have tried all these with pymatgen before. All the setup requires etc do not work. For pymatgen, we simply throw a useful error message if numpy cannot be imported to tell people to install numpy first. Also, it is good to point people to use conda by default. It solves a lot of issues with dependencies. Most casual users do not have the capability to deal with extensions on Windows without conda.

**Comment by atztogo** [comment]
Thanks @shyuep for your information. It's helpful.

**Comment by jochym** [comment]
Can we close this issue? I think it is 'kind of' solved in current version (next release).

**Comment by atztogo** [comment]
Can we close this issue?

**Comment by jochym** [comment]
I think we can. I do not know any technique to handle numpy dependence better. I vote for closing.
