### ISSUE TITLE
Work-around for http://bugs.python.org/issue21121

### ISSUE THREAD

**Issue by glaweh** [atztogo/spglib#17]
Hi,
Linux Distribution SLES 12.1, frequently used on supercomputers, does only contain python3 3.4.1, which is subject to http://bugs.python.org/issue21121 (fixed in python3 3.4.2).
Could you insert something like

os.environ['CFLAGS'] = sysconfig.get_config_var("CFLAGS").replace("-Werror=declaration-after-statement", "")

to strip that -Werror from the CFLAGS used to compile spglib? Otherwise, the build fails

regards,
Henning

**Comment by atztogo** [comment]
I added lines to setup.py in the develop branch. See https://github.com/atztogo/spglib/commit/e866d21033249aa35ff663ffb9084c600a957ce3 .
Hopefully this will be OK.

Togo

**Comment by glaweh** [comment]
I checked with an affected python 3.4.1, and it works as expected.

Thanks,
Henning

**Comment by nfette** [comment]
CFLAGS is not defined in my environment, and at the moment install fails both via pip and setup.py. I am trying to install from source after making this change:
```
if config_var and "-Werror=declaration-after-statement" in config_var:
    ...
```

**Comment by shyuep** [comment]
I already pushed a change to fix this. @atztogo I suggest you issue a bug fix release. This problem is causing many spglib python installations to fail.

**Comment by atztogo** [comment]
I see.
