### ISSUE TITLE
installation fails on Windows due to no CFLAGS config var

### ISSUE THREAD

**Issue by dwinston** [atztogo/spglib#22]
In [setup.py](https://github.com/atztogo/spglib/blob/951c47ced2ac08f5963ad6554a136e052459d294/python/setup.py#L21):
```python
import sysconfig
config_var = sysconfig.get_config_var("CFLAGS")
if "-Werror=declaration-after-statement" in config_var:
    os.environ['CFLAGS'] = config_var.replace(
        "-Werror=declaration-after-statement", "")    
```
Fails with
```error
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    if "-Werror=declaration-after-statement" in config_var:
TypeError: argument of type 'NoneType' is not iterable
```
because `config_var` is `None` on my system (Windows, Conda Python 3). You could perhaps change the condition to be `if config_var and ("-Werror=declaration-after-statement" in config_var):`.

My end goal is to install spglib in a windows conda py3 environment, so if you could conda build windows versions as part of your [conda build procedure](https://github.com/atztogo/spglib/tree/951c47ced2ac08f5963ad6554a136e052459d294/python/conda) when you release new versions, that would be ideal.

Thank you for maintaining such an excellent library!

**Comment by dwinston** [comment]
Oh wow, I just saw https://github.com/atztogo/spglib/commit/9e25244933e65c67930829c174456ded6799b3c7, so I guess this will be solved in the next release?

**Comment by atztogo** [comment]
Yes. Please wait for a while to prepare the conda (and PyPI) package with this fix.

**Comment by atztogo** [comment]
But anyway thanks for reporting it. By this I could know there are at least some (and possibly more) spglib users on windows, which was beyond my imagination.

**Comment by protik77** [comment]
Another windows user here. I am trying to install [pymatgen](http://pymatgen.org/) where spglib is part of the dependencies. They have extensive [instructions](http://pymatgen.org/installation.html) on installing pymatgen on windows so I believe that is possible.

For a workaround I downloaded the version 1.9.5 and changed line 22 of the setup.py to the line of 1.9.6 and it was a success. But now I am getting huge number of errors. Most of the errors are syntax error like,

`  _spglib.c(536) : error C2143: syntax error : missing ';' before 'type'`

The final errors are:

1. error: Command "C:\Users\Protik\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc -IC:\Users\Protik\Miniconda2\envs\ptk_pymatgen\lib\site-packages\numpy\core\include -IC:\Users\Protik\Miniconda2\envs\ptk_pymatgen\include -IC:\Users\Protik\Miniconda2\envs\ptk_pymatgen\PC /Tc_spglib.c /Fobuild\temp.win-amd64-2.7\Release\_spglib.obj" failed with exit status 2 

Failed building wheel for spglib 

2. error: Command "C:\Users\Protik\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc -IC:\Users\Protik\Miniconda2\envs\ptk_pymatgen\lib\site-packages\numpy\core\include -IC:\Users\Protik\Miniconda2\envs\ptk_pymatgen\include -IC:\Users\Protik\Miniconda2\envs\ptk_pymatgen\PC /Tc_spglib.c /Fobuild\temp.win-amd64-2.7\Release\_spglib.obj" failed with exit status 2 

Command "C:\Users\Protik\Miniconda2\envs\ptk_pymatgen\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\protik\\appdata\\local\\temp\\pip-6rn7rt-build\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\protik\appdata\local\temp\pip-qzl5zr-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\protik\appdata\local\temp\pip-6rn7rt-build\

I understand it's a lot to ask to modify the whole code base for windows, but some workaround will be appreciated.

**Comment by shyuep** [comment]
Fyi, you can try installing 1.9.4.4 in the meantime. I know for certain that works on Windows. Do pip install spglib==1.9.4.4 before installing pymatgen.

**Comment by shyuep** [comment]
Also, the conda instructions for installing pymatgen on Windows has been tested only with python 3.5. I suggest you use py35 unless you know you have other dependencies that require py27

**Comment by shyuep** [comment]
Note that this means downloading miniconda3, not miniconda2 like you have done.

**Comment by protik77** [comment]
Thanks a lot @shyuep ! Installed miniconda with python 3.5 and then the spglib 1.9.4.4. Everything worked out nicely.

**Comment by shyuep** [comment]
@atztogo There are a lot of Windows users. Esp for pymatgen, and that relies on spglib. :-)

**Comment by atztogo** [comment]
Indeed! I'm sorry for the delay!

**Comment by atztogo** [comment]
Now spglib-1.9.6 is ready for PyPI and conda (thanks @jochym !).

Currently the test is done for ubuntu-trusty on travis-CI, and not made for windows, mac, and for the ohter linux distributions if I understand correctly the spglib travis-CI setting. So if you find any problems, please let me know.

**Comment by protik77** [comment]
@atztogo Worked perfectly in my windows machine. I am using conda3 in a windows 10 machine.

**Comment by shyuep** [comment]
I think this issue can be closed.

**Comment by shyuep** [comment]
Note that I have officially compiled Windows and OSX versions of pymatgen + spglib. You can install them via the "materials" channel. E.g.,

```
conda install -c materials pymatgen spglib
```

This should take care of WIndows and Mac users on Py35. Linux users should not have issues via pip install anyway.

**Comment by atztogo** [comment]
Do you think this information is good to be written on the spglib document? For example, "For the pymatgen users, bra bra bra ..."

**Comment by shyuep** [comment]
@atztogo Sure. Esp if people wants to install spglib on Windows.
