### ISSUE TITLE
Wrong hall_number and international space group name obtained from get_symmetry_dataset

### ISSUE THREAD

**Issue by afonari** [atztogo/spglib#32]
```python
import spglib

# Water molecule in a box
vecs = [[3.68678289, 0., 0.], [0., 2.53729961, 0.], [0., 0., 2.]]
coords = [[0., 0., 0.],
          [0.22876069, 0.21176057, 0.],
          [0.77123931, 0.21176057, 0.]]

anums = [8, 1, 1]

cell = (vecs, coords, anums)
dataset = spglib.get_symmetry_dataset(cell)

print 'From dataset:'
print dataset['hall_number']
print dataset['international']
print dataset['rotations']

print 'From database for hall_number = 125:'
print spglib.get_symmetry_from_database(dataset['hall_number'])['rotations']

print 'From database for hall_number = 127 group:'
print spglib.get_symmetry_from_database(127)['rotations']
```

This outputs:
```
From dataset:
125
Pmm2
[[[ 1  0  0]
  [ 0  1  0]
  [ 0  0  1]]

 [[-1  0  0]
  [ 0  1  0]
  [ 0  0 -1]]

 [[ 1  0  0]
  [ 0  1  0]
  [ 0  0 -1]]

 [[-1  0  0]
  [ 0  1  0]
  [ 0  0  1]]]
From database for hall_number = 125:
[[[ 1  0  0]
  [ 0  1  0]
  [ 0  0  1]]

 [[-1  0  0]
  [ 0 -1  0]
  [ 0  0  1]]

 [[-1  0  0]
  [ 0  1  0]
  [ 0  0  1]]

 [[ 1  0  0]
  [ 0 -1  0]
  [ 0  0  1]]]
From database for hall_number = 127 group:
[[[ 1  0  0]
  [ 0  1  0]
  [ 0  0  1]]

 [[ 1  0  0]
  [ 0  1  0]
  [ 0  0 -1]]

 [[-1  0  0]
  [ 0  1  0]
  [ 0  0  1]]

 [[-1  0  0]
  [ 0  1  0]
  [ 0  0 -1]]]
```

It seems that in the dataset, rotations are correct (pointing to P m 2 m (hall_number = 127) group). However, both dataset['hall_number'] and dataset['international'] (125, Pmm2) are wrong. The correct values would be 127, P m 2 m, respectively.

**Comment by atztogo** [comment]
Spglib is not sure if lattice vectors that  a user gives to spglib follow crystallographic convention or not. Cartesian coordinates are used to obtain matrix&vector representation of space group operations but are useless for identifying space group, since it's a group theoretical object. For example, rotating a crystal in the Cartesian coordinates changes nothing about the symmetry.

dataset['rotations'] and dataset['translations'] are returned with respect to the user's lattice vectors. The lattice vectors can be that for a supercell or the linear combinations, e.g., a and b axes are flipped or (a + b, b, c) may be chosen than a usual choice, and supercell is not handled in the frame work of normal crystallography (I think).

After space group type determination, dataset['hall_number'] is given as the first (top) one in the list of Hall symbol in http://pmsl.planet.sci.kobe-u.ac.jp/~seto/?page_id=37&lang=en corresponding to the space group type. This is the spglib's choice. There are three Hall symbols (125, 126, 127) corresponding to space group number 25, many-to-one correspondence. By this, spglib chooses 125. If you want to match with Hall symbols of 127, spg_get_dataset_with_hall_number (C-API) can be used. But just now I realized that no Python method is prepared for this function. I will make it.

**Comment by afonari** [comment]
Thank you for the extended explanation, I understand better what is going on now.

>  that no Python method is prepared for this function. I will make it.

Thank would be great, thank you.

**Comment by atztogo** [comment]
I pushed the update to the master branch. I hope this is what you are interested in, but maybe not. The example is shown below.

```python
import spglib

# Water molecule in a box
vecs = [[3.68678289, 0., 0.], [0., 2.53729961, 0.], [0., 0., 2.]]
coords = [[0., 0., 0.],
          [0.22876069, 0.21176057, 0.],
          [0.77123931, 0.21176057, 0.]]
anums = [8, 1, 1]
cell = (vecs, coords, anums)

print('From dataset without hall_number keyword:')
dataset = spglib.get_symmetry_dataset(cell)
print(dataset['hall_number'])
print(dataset['international'])
print(dataset['std_lattice'])
for i in range(125, 128):
    print('')
    print('From dataset with hall_number=%d:' % i)
    dataset = spglib.get_symmetry_dataset(cell, hall_number=i)
    print(dataset['hall_number'])
    print(dataset['international'])
    print(dataset['std_lattice'])
```
The output is:
```
From dataset without hall_number keyword:
125
Pmm2
[[ 2.          0.          0.        ]
 [ 0.          3.68678289  0.        ]
 [ 0.          0.          2.53729961]]

From dataset with hall_number=125:
125
Pmm2
[[ 2.          0.          0.        ]
 [ 0.          3.68678289  0.        ]
 [ 0.          0.          2.53729961]]

From dataset with hall_number=126:
126
P2mm
[[ 2.53729961  0.          0.        ]
 [ 0.          2.          0.        ]
 [ 0.          0.          3.68678289]]

From dataset with hall_number=127:
127
Pm2m
[[ 2.          0.          0.        ]
 [ 0.          2.53729961  0.        ]
 [ 0.          0.          3.68678289]]
```

**Comment by afonari** [comment]
I realized by looking into API more carefully that I might be able to use:

hall_number = get_hall_number_from_symmetry(rotations, translations, symprec)

When I try to do that on the original example:

```python
import spglib

# Water molecule in a box
vecs = [[3.68678289, 0., 0.], [0., 2.53729961, 0.], [0., 0., 2.]]
coords = [[0., 0., 0.],
          [0.22876069, 0.21176057, 0.],
          [0.77123931, 0.21176057, 0.]]

anums = [8, 1, 1]

symprec = 1e-5

cell = (vecs, coords, anums)
dataset = spglib.get_symmetry_dataset(cell)

print 'From dataset:'
print dataset['hall_number']
print dataset['international']
print dataset['rotations']

print ''
print 'From get_hall_number_from_symmetry:'
print spglib.get_hall_number_from_symmetry(dataset['rotations'], dataset['translations'], symprec)
```

```
From dataset:
125
Pmm2
[[[ 1  0  0]
  [ 0  1  0]
  [ 0  0  1]]

 [[-1  0  0]
  [ 0  1  0]
  [ 0  0 -1]]

 [[ 1  0  0]
  [ 0  1  0]
  [ 0  0 -1]]

 [[-1  0  0]
  [ 0  1  0]
  [ 0  0  1]]]

From get_hall_number_from_symmetry:
125
```
get_hall_number_from_symmetry returns hall_number for standard orientation cell, not hall_number for actual rotations. Function calls go as follows:

get_hall_number_from_symmetry -> py_get_hall_number_from_symmetry -> spg_get_hall_number_from_symmetry -> prm_get_primitive_symmetry, here where it goes wrong:
```C
int spg_get_hall_number_from_symmetry(SPGCONST int rotation[][3][3],
                                      SPGCONST double translation[][3],
                                      const int num_operations,
                                      const double symprec)
{
  int i;
  Symmetry *symmetry;
  Symmetry *prim_symmetry;
  Spacegroup spacegroup;

  symmetry = NULL;
  prim_symmetry = NULL;

  symmetry = sym_alloc_symmetry(num_operations);
  for (i = 0; i < num_operations; i++) {
    mat_copy_matrix_i3(symmetry->rot[i], rotation[i]);
    mat_copy_vector_d3(symmetry->trans[i], translation[i]);
  }

  prim_symmetry = prm_get_primitive_symmetry(symmetry, symprec);
  spacegroup = spa_search_spacegroup_with_symmetry(prim_symmetry, symprec);
```

prm_get_primitive_symmetry converts symmetry to prim_symmetry, and spa_search_spacegroup_with_symmetry is only able to return space group with standard orientation, in this case Pmm2 (125) and not Pm2m (127).

Sorry for finding this only now, hope this makes it more clear what is the issue.

**Comment by atztogo** [comment]
No, it is not wrong. I (spglib) suppose that rotation matrices and translations can be different from the standard ones, where my standard representation is generated by Hall symbol, http://cci.lbl.gov/sginfo/hall_symbols.html. Otherwise how can spglib know if the input is standard or not and how can spglib run the database match for general inputs? In other words, it's your choice among 125, 126, or 127, but it's not possible to be determined by spglib from the set of symmetry operations since these three represent the same space group type (the same abstract group). If you doubt what I write, please read text books of crystallography, e.g., 'Symmetry Relationships between Crystal Structures. Applications of Crystallographic Group Theory in Crystal Chemistry' by Ulrich Müller. Then if you have a better idea, e.g., algorithm or definition of convention, I'm very happy to hear it.

**Comment by afonari** [comment]
> In other words, it's your choice among 125, 126, or 127, but it's not possible to be determined by spglib from the set of symmetry operations since these three represent the same space group type (the same abstract group).

I thought there is one to one correspondence between rotations + translations and hall number (and as the result space group with setting).

**Comment by afonari** [comment]
Here what I came up with:
```python
import spglib
import numpy


def equal_rotations(rotations1, rotations2):
    shape1 = numpy.shape(rotations1)
    shape2 = numpy.shape(rotations2)

    if not (shape1 == shape2):
        return False

    rots1_1d = [None] * shape1[0]
    rots2_1d = [None] * shape1[0]
    for idx, (rot1, rot2) in enumerate(zip(rotations1, rotations2)):
        rots1_1d[idx] = ''.join(map(str, rot1.flat))
        rots2_1d[idx] = ''.join(map(str, rot2.flat))

    return len(set(rots1_1d).intersection(rots2_1d)) == shape1[0]


spacegroup_to_hall_number = [
    1,   2,   3,   6,   9,  18,  21,  30,  39,  57,
   60,  63,  72,  81,  90, 108, 109, 112, 115, 116,
  119, 122, 123, 124, 125, 128, 134, 137, 143, 149,
  155, 161, 164, 170, 173, 176, 182, 185, 191, 197,
  203, 209, 212, 215, 218, 221, 227, 228, 230, 233,
  239, 245, 251, 257, 263, 266, 269, 275, 278, 284,
  290, 292, 298, 304, 310, 313, 316, 322, 334, 335,
  337, 338, 341, 343, 349, 350, 351, 352, 353, 354,
  355, 356, 357, 358, 359, 361, 363, 364, 366, 367,
  368, 369, 370, 371, 372, 373, 374, 375, 376, 377,
  378, 379, 380, 381, 382, 383, 384, 385, 386, 387,
  388, 389, 390, 391, 392, 393, 394, 395, 396, 397,
  398, 399, 400, 401, 402, 404, 406, 407, 408, 410,
  412, 413, 414, 416, 418, 419, 420, 422, 424, 425,
  426, 428, 430, 431, 432, 433, 435, 436, 438, 439,
  440, 441, 442, 443, 444, 446, 447, 448, 449, 450,
  452, 454, 455, 456, 457, 458, 460, 462, 463, 464,
  465, 466, 467, 468, 469, 470, 471, 472, 473, 474,
  475, 476, 477, 478, 479, 480, 481, 482, 483, 484,
  485, 486, 487, 488, 489, 490, 491, 492, 493, 494,
  495, 497, 498, 500, 501, 502, 503, 504, 505, 506,
  507, 508, 509, 510, 511, 512, 513, 514, 515, 516,
  517, 518, 520, 521, 523, 524, 525, 527, 529, 530,
]


# Water molecule in a box
vecs = [[3.68678289, 0., 0.], [0., 2.53729961, 0.], [0., 0., 2.]]
coords = [[0., 0., 0.],
          [0.22876069, 0.21176057, 0.],
          [0.77123931, 0.21176057, 0.]]

anums = [8, 1, 1]

symprec = 1e-5

cell = (vecs, coords, anums)
dataset = spglib.get_symmetry_dataset(cell)

print 'From dataset:'
print dataset['hall_number']
print dataset['international']
print dataset['translations']
print dataset['rotations']

spg_type = spglib.get_spacegroup_type(dataset['hall_number'])

hall_num_start = spacegroup_to_hall_number[dataset['number'] - 1]
hall_num_end = spacegroup_to_hall_number[dataset['number']]

for hall_num in range(hall_num_start, hall_num_end):
    symm = spglib.get_symmetry_from_database(hall_num)

    trans_close = numpy.allclose(symm['translations'], dataset['translations'])

    if trans_close and equal_rotations(symm['rotations'], dataset['rotations']):
        spg_type = spglib.get_spacegroup_type(hall_num)
        break

print spg_type['international_full']
```

This prints out the correct international symbol for that set of rotations/translations:
```
From dataset:
125
Pmm2
[[-0. -0. -0.]
 [-0. -0. -0.]
 [-0. -0. -0.]
 [-0. -0. -0.]]
[[[ 1  0  0]
  [ 0  1  0]
  [ 0  0  1]]

 [[-1  0  0]
  [ 0  1  0]
  [ 0  0 -1]]

 [[ 1  0  0]
  [ 0  1  0]
  [ 0  0 -1]]

 [[-1  0  0]
  [ 0  1  0]
  [ 0  0  1]]]
P m 2 m
```

Does this make sense? Can this be introduced into C/Python distribution. Not sure if equal_rotations(rotations1, rotations2) is the best implementation.

**Comment by atztogo** [comment]
This doesn't make sense. For example, how do treat rigid translation?
```python
coords = numpy.array(coords) + 0.01
```

**Comment by afonari** [comment]
Not sure I understand the connection between rigid translations and hall_numbers. Maybe you think of standard-orientation cell and I refer to original (not necessarily standard-orientation cell).

**Comment by atztogo** [comment]
I just showed that your code is unable to use in general case, i.e., wild inputs of spglib users.

Finally I lost to see what is your problem. Probably you think you understand what you are doing but I know these stuffs are not intuitive at all than that you might think. We need common understandings about the theory, definitions and conventions about crystallography to continue this discussion.

Can I close this issue?

**Comment by atztogo** [comment]
I wrote some document how to use `hall_number` at https://atztogo.github.io/spglib/python-spglib.html#get-symmetry-dataset. I put some useful references about crystallographic definitions and conventions at https://atztogo.github.io/spglib/definition.html#references. I hope this will make some understanding each other.

**Comment by afonari** [comment]
Thanks a lot for the explanations and references. I will definitely go over them and will try ot understand. The issue can be closed now.
