### ISSUE TITLE
standardize_cell fails for rhombohedral cell

### ISSUE THREAD

**Issue by aoterodelaroza** [atztogo/spglib#35]
Hi,

This minimal python example:

cell = ([(10.0000000000, 0.0000000000, 0.0000000000),
         (6.4278760969,  7.6604444312, 0.0000000000),
         (6.4278760969,  2.9973678496, 7.0496946641)],
        [(0,0,0)],
        [1])
lattice, positions, numbers = standardize_cell(cell,to_primitive=0,no_idealize=1,symprec=1e-5)

fails with "floating point exception". The structure is a simple rhombohedral lattice with a = 10 and alpha = 50 degrees. It seems like spglib is detecting an H setting. For instance,

dataset = get_symmetry_dataset(cell)
print(dataset['choice'])

gives "H". Then it tries to convert from hexagonal to trigonal axes, and fails because the cell was primitive in the first place.

Thanks!

**Comment by atztogo** [comment]
Thanks @aoterodelaroza. I confirmed the crash. I will fix this problem, This may take some time.

**Comment by atztogo** [comment]
This case, primitive cell to conventional unit cell, was simply not considered. I consider the algorithm and wrote some code. I hope that this problem has been fixed and the fixed code is found in the develop branch. I've not yet been very much confident and so the code is not yet merged to the master branch.

**Comment by aoterodelaroza** [comment]
Thanks @atztogo ! It seems to be working for me. I am running more tests on a collection of crystals (~1000) and getting some occasional crashes. I will try solve them myself first and do a PR against the develop branch if I can, or submit an issue with a minimal example if I can't.
