### ISSUE TITLE
Cyclic behavior of standardize_cell

### ISSUE THREAD

**Issue by aoterodelaroza** [atztogo/spglib#38]
Hi,

I'm not sure if this is a bug, but I've been finding some weird occasional behavior from standardize_cell. It is illustrated by this example:

```python
from spglib import *

lattice = [
(  12.5458917962 ,  0.0000000000 ,  0.0000000000     ),
(   0.0000000000 , 12.5458917962 ,  0.0000000000     ),
(   0.0000000000 ,  0.0000000000 , 16.8525776531     )]

positions = [
( 0.00000000 ,  0.00000000 ,  0.19800000),
( 0.00000000 ,  0.00000000 ,  0.80200000),
( 0.50000000 ,  0.50000000 ,  0.30200000),
( 0.50000000 ,  0.50000000 ,  0.69800000),
( 0.97380000 ,  0.18620000 ,  0.09920000),
( 0.81380000 ,  0.97380000 ,  0.90080000),
( 0.02620000 ,  0.81380000 ,  0.09920000),
( 0.18620000 ,  0.02620000 ,  0.90080000),
( 0.52620000 ,  0.68620000 ,  0.40080000),
( 0.68620000 ,  0.47380000 ,  0.59920000),
( 0.47380000 ,  0.31380000 ,  0.40080000),
( 0.31380000 ,  0.52620000 ,  0.59920000),
( 0.16000000 ,  0.21220000 ,  0.00000000),
( 0.78780000 ,  0.16000000 ,  0.00000000),
( 0.84000000 ,  0.78780000 ,  0.00000000),
( 0.21220000 ,  0.84000000 ,  0.00000000),
( 0.34000000 ,  0.71220000 ,  0.50000000),
( 0.71220000 ,  0.66000000 ,  0.50000000),
( 0.66000000 ,  0.28780000 ,  0.50000000),
( 0.28780000 ,  0.34000000 ,  0.50000000),
( 0.11560000 ,  0.00990000 ,  0.26880000),
( 0.99010000 ,  0.11560000 ,  0.73120000),
( 0.88440000 ,  0.99010000 ,  0.26880000),
( 0.00990000 ,  0.88440000 ,  0.73120000),
( 0.38440000 ,  0.50990000 ,  0.23120000),
( 0.50990000 ,  0.61560000 ,  0.76880000),
( 0.61560000 ,  0.49010000 ,  0.23120000),
( 0.49010000 ,  0.38440000 ,  0.76880000),
( 0.96450000 ,  0.30160000 ,  0.15900000),
( 0.69840000 ,  0.96450000 ,  0.84100000),
( 0.03550000 ,  0.69840000 ,  0.15900000),
( 0.30160000 ,  0.03550000 ,  0.84100000),
( 0.53550000 ,  0.80160000 ,  0.34100000),
( 0.80160000 ,  0.46450000 ,  0.65900000),
( 0.46450000 ,  0.19840000 ,  0.34100000),
( 0.19840000 ,  0.53550000 ,  0.65900000),
( 0.28170000 ,  0.23030000 ,  0.06260000),
( 0.76970000 ,  0.28170000 ,  0.93740000),
( 0.71830000 ,  0.76970000 ,  0.06260000),
( 0.23030000 ,  0.71830000 ,  0.93740000),
( 0.21830000 ,  0.73030000 ,  0.43740000),
( 0.73030000 ,  0.78170000 ,  0.56260000),
( 0.78170000 ,  0.26970000 ,  0.43740000),
( 0.26970000 ,  0.21830000 ,  0.56260000),
( 0.14270000 ,  0.32860000 ,  0.94300000),
( 0.67140000 ,  0.14270000 ,  0.05700000),
( 0.85730000 ,  0.67140000 ,  0.94300000),
( 0.32860000 ,  0.85730000 ,  0.05700000),
( 0.35730000 ,  0.82860000 ,  0.55700000),
( 0.82860000 ,  0.64270000 ,  0.44300000),
( 0.64270000 ,  0.17140000 ,  0.55700000),
( 0.17140000 ,  0.35730000 ,  0.44300000)]

numbers = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ]

for i in range(0,5):
    cell = (lattice,positions,numbers)
    dataset = get_symmetry_dataset(cell)
    print "** Step %d **" % i
    print "atom number 4:"
    print cell[1][4]
    print "tmatrix: "
    print dataset['transformation_matrix']
    print ""
    lattice, positions, numbers = standardize_cell(cell,to_primitive=0,no_idealize=1,symprec=1e-5)
```

which gives the following output:

```
** Step 0 **
atom number 4:
(0.9738, 0.1862, 0.0992)
tmatrix: 
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]

** Step 1 **
atom number 4:
[ 0.8138  0.9738  0.0992]
tmatrix: 
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]

** Step 2 **
atom number 4:
[ 0.0262  0.8138  0.0992]
tmatrix: 
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]

** Step 3 **
atom number 4:
[ 0.1862  0.0262  0.0992]
tmatrix: 
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]

** Step 4 **
atom number 4:
[ 0.9738  0.1862  0.0992]
tmatrix: 
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
```

So standardize_cell always performs the same transformation using the matrix indicated in any of the steps. Since R^4 = I for that matrix, it takes four steps to cycle back to the original structure. From the documentation, one would expect standardize_cell to transform to, well, the standard cell for the current space group. Shouldn't the transformation matrix be the identity after the first step?

Thanks for your work! :)

**Comment by atztogo** [comment]
In finding space group type or crystallographic information, a bit complicated steps (for me) are implemented. There are many steps that are not determined uniquely, etc, to find any one of primitive cells that is not unique. So the input structure changes, the result can change in spglib, but  at least the result is expected to be crystallographically correct, i.e., groups, choices, etc of cells of your steps are equivalent. Your test is for me that accepted as a correct behaviour of current spglib though it looks for us to be a weird behaviour. I think this is the gap that exists between non-crystallographers and crystallographers and I belong the former. To make it natural for us, I probably need a lot of effort to define mathematical or algorithmical mechanism to pin the lattice in Cartesian coordinates as the first one, but the user's input is not always clean as you might think, e.g., lattice vectors are not align those expected in Cartesian coordinates. To treat many strange cases, I want to give up complicated procedures, which eases the implementation and maintenance and also for avoiding bugs. So I want you to accept it if it doesn't result in severe problem for you. There may be a good idea and an easy solution, but for it I have little time to do and I don't work for it unless I am strongly pushed by some motivation.

**Comment by aoterodelaroza** [comment]
I see, thanks for the explanation! It is certainly no big deal and certainly not worth worrying over it (I'll just make a note of it in my manual). A weaker version of my question: is there any way of determining if a given input cell is standard or not?

**Comment by atztogo** [comment]
It's a good idea. If an input cell is transformed to a standardized cell (in spglib definition) by a generator of the Euclidean normalizer (see e.g., http://reference.iucr.org/dictionary/Normalizer), then it is, I think.

**Comment by aoterodelaroza** [comment]
Ah, so then it'd be just a matter of determining whether the transformation_matrix generates the Euclidean normalizer. I'll mull it over and do some tinkering. Thanks again! This is very very useful. :+1:
