### ISSUE TITLE
spglib.c:647: bad test ?

### ISSUE THREAD

**Issue by dcb314** [atztogo/spglib#40]
spglib.c:647]: (warning) Logical disjunction always evaluates to true: hall_number > 0 || hall_number < 531.

Source code is

  if (0 < hall_number || hall_number < 531) {

**Comment by atztogo** [comment]
Thanks. I think this was fixed by another pull request, https://github.com/atztogo/spglib/commit/5e0d71fa50cf7de5d4fd2e45ffdbc60bd5bdb50a.

**Comment by atztogo** [comment]
I close this issue because it is already fixed.
