### ISSUE TITLE
Undefined symbols det_free_container, det_determine_all

### ISSUE THREAD

**Issue by antonio-rojas** [atztogo/spglib#41]
Compiling spglib 1.10.1 (and git master) gives two unresolved symbols in libsymspg.so:
```
DYNAMIC SYMBOL TABLE:
0000000000000000      D  *UND*  0000000000000000              det_determine_all
0000000000000000      D  *UND*  0000000000000000              det_free_container
```
This breaks compilation of avogadro against spglib 1.10.1.
Using GCC 7.2.0 with 
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt"
CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"

**Comment by atztogo** [comment]
There are two new files added in this version, `determination.c` and `determination.h`. I forgot to add them to `src/Makefile.am`.

**Comment by antonio-rojas** [comment]
Thanks, I confirm it's OK on git master now.

**Comment by atztogo** [comment]
Thanks for letting me know this issue.
