### ISSUE TITLE
determination.h is not installed via 'make install'

### ISSUE THREAD

**Issue by merkys** [atztogo/spglib#42]
I am attempting to prepare a Debian package from spglib v1.10.1. However, it occurs to me that header file ``determination.h``, which is included in ``spglib.c`` and ``determination.c``, is not installed in ``/usr/include/spglib/`` by standard ``make install``. I suppose this is a bug as ``determination.c`` is added recently and possibly its header is not set up to be installed properly.

**Comment by atztogo** [comment]
I think it's fixed at issure #41. If so, my question is about versioning. I don't want to make github releases for all minor fixes, instead the latest released version including minor fixes is found at https://github.com/atztogo/spglib/archive/master.zip. It is written here, https://atztogo.github.io/spglib/install.html. Is this fine or maybe confusing?

**Comment by merkys** [comment]
Thank you for pointing this out, I have not checked the code in master. However, it would be better to use the released version for distribution at least in Debian packaging. On the other hand I could use GIT commit ID to uniquely identify the code between releases.

**Comment by atztogo** [comment]
> it would be better to use the released version for distribution

I can understand. If 4th version number is allowed, you can see it by git describe --tags, which is the same trick to make the (nano) version number shown at https://pypi.python.org/pypi/spglib.

**Comment by merkys** [comment]
I see. However, it's a bit tricky for Debian as Debian relies upon a mechanism based on [watch file for ``uscan``](https://wiki.debian.org/debian/watch), which essentially queries an URL, parses it and looks for tar.gz files to determine what versions of a package are available.

For now I have made a patch from issue #41 on top of source of v1.10.1. I have submitted the resulting package for review of Debian Developers. Hopefully someone notices it soon.

**Comment by atztogo** [comment]
I see. Then the best solution would be to increment the version number. So I made the tag, v1.10.2. I rarely use autoconf system for spglib now. So I didn't have enough attention for that, but I should have done it. I am sorry for my late action after you made the patch.

**Comment by merkys** [comment]
Thank you very much for the release. I will update the Debian package accordingly to v1.10.2.
