### ISSUE TITLE
symPoscar.rb:  undefined symbol: spgat_get_symmetry_numerical

### ISSUE THREAD

**Issue by asubedi** [atztogo/spglib#46]
I get the following error when I try to use symPoscar.rb:

/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': /home/subedi/scratch/softwares/spglib-1.10.3/ruby/getspg.so: undefined symbol: spgat_get_symmetry_numerical - /home/subedi/scratch/softwares/spglib-1.10.3/ruby/getspg.so (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from symPoscar.rb:26:in `<main>'

While compiling the ruby module, there was this warning:
getspg.c: In function ‘method_get_symmetry’:
getspg.c:321:13: warning: implicit declaration of function ‘spgat_get_symmetry_numerical’; did you mean ‘spgat_get_symmetry’? [-Wimplicit-function-declaration]
   num_sym = spgat_get_symmetry_numerical(rotations,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
             spgat_get_symmetry

Everything runs fine if I make the change according to the warning.

**Comment by atztogo** [comment]
Thanks for your information. I haven't maintained the ruby module for many years. I will have a look and hopefully fix it.

**Comment by asubedi** [comment]
It works very nicely with the change suggested by the warning. 

I am a heavy user of the ruby module. It's very handy to quickly check the symmetry of the structure and print out the primitive/conventional cell when one is doing full structural relaxations.

**Comment by atztogo** [comment]
I never thought somebody uses the ruby module. It's good to hear it for me. I will fix following your advice. Thanks.

**Comment by atztogo** [comment]
The fix is done. Now it's in the master branch.

**Comment by atztogo** [comment]
I close this issue.
