### ISSUE TITLE
ASE atoms transpose in documentation

### ISSUE THREAD

**Issue by peder2tm** [atztogo/spglib#49]
In the section of the documentation about deprecation of ASE atoms object
https://atztogo.github.io/spglib/python-spglib.html#crystal-structure-cell
I think it is misleading that the cell matrix is transposed, i.e.
`lattice = np.array(cell.get_cell().T, dtype='double', order='C')`
As far as I can see the ASE atoms cell has the correct orientation for the Python API.
If I define the cell tuple using the example in the documentation
`cell = (lattice, positions, numbers)`
and call `spglib.get_spacegroup(cell)`
I get a different result from `spg.get_spacegroup(ase_atoms)` unless I omit the transpose from the documentation.

**Comment by atztogo** [comment]
Thanks. You are correct. I fixed it. In fact, internally [the code  is written like C-spglib-API style](https://github.com/atztogo/spglib/blob/e0851894ccdad1abb87d519b228d056128b56806/python/spglib/spglib.py#L737-L741), but for users, it should be shown in the python-spglib-API format here on the documentation.

**Comment by peder2tm** [comment]
Yes, it makes sense that this is what the code does internally
