### ISSUE TITLE
Version of libsymspg.so.X.Y.Z is not set propertly if built via autotools

### ISSUE THREAD

**Issue by merkys** [atztogo/spglib#52]
According to README.md, there are two ways of building the spglib. cmake produces libsymspg.so.X.Y.Z where X.Y.Z correspond to major, minor and micro versions of the package, which is the intended behavior. However, autotools produce libsymspg.so.0.0.0 no matter which source version is used. I suppose this is a bug.

**Comment by atztogo** [comment]
True. But autotools is difficult to use and I am not sure the versioning convention. So if we want to be strict, rather I want to abandon it.

**Comment by merkys** [comment]
Makes sense. I have used autotools to prepare a Debian package for spglib, but I will try to switch to cmake build system in order to get the version right.

**Comment by merkys** [comment]
I consider this issue closed, although it would be nice to see a deprecation warning of autotools in README.md, just to let the other users know.
