### ISSUE TITLE
Feature request : PyPI releases as wheels

### ISSUE THREAD

**Issue by LaurentRDC** [atztogo/spglib#61]
Hello,

Would it be possible to upload wheels to PyPI for new releases? I've included spglib as a dependency for [this project](https://pypi.org/project/iris-ued/) and Windows users are required to install at least the Visual Studio Build Tools (~5GB) just to install spglib. 

Wheels would remove the requirement of having a C compiler available.

**Comment by atztogo** [comment]
I don't use windows, so I have quite no idea. Do you know the best way to do it?
Spglib wheels for linux are made on travis-CI. It may be possible to make the wheel for windows on AppVeyor, but I have no experience for AppVeyor yet.

**Comment by jochym** [comment]
I would suggest to switch to miniconda + conda-forge for windows users. You are bound to need to install some more python packages eventually. The packages are auto-build and quite current. And you get nice python setup and environment designed for the desktop user.
OTOH @atztogo making other packages (Win, OSX) is a substantial amount of work and requires frequent tweaks to adapt to changing CI services. This work is already done by the conda-forge project. I think setting up a second and third CI chain will be unnecessary duplication of effort. I advice against it and being a co-author of current deploy system and conda-forge packages I have no plans to do it.

**Comment by atztogo** [comment]
I leave the link, https://anaconda.org/conda-forge/spglib .

**Comment by LaurentRDC** [comment]
Thank you for both your answers.

I had not realized that the building process was automated. I do not want to burden you. @jochym I think you are right, the best way to release packages is probably to do it through conda-forge. I will look into it.
