### ISSUE TITLE
Primitive atom consistency

### ISSUE THREAD

**Issue by atztogo** [atztogo/spglib#67]
This issue is moved from spglib mailing list ( https://sourceforge.net/p/spglib/mailman/message/36454767/ )since here is easier to communicate when using code snippet etc.

**Comment by atztogo** [comment]
What is done in standardization is very tricky. The one stardardized (`std_mapping_to_primitive`) and not starndarized (`mapping_to_primitive`) are originated in different ways. So the purpose to prepare `std_*` are for the user like you to rely only `std_*` functions but not `mapping_to_primitive`. What you need extra is the transformation matrix from primitive basis vectors from your original basis vectors that should be written in combination of a rigid rotation and an integer matrix. I think we discussed this at 
https://sourceforge.net/p/spglib/mailman/spglib-users/thread/D0A79931-6AFE-40BB-B910-A436B61A316C@nrl.navy.mil/

`mapping_to_primitive` is used with non-standardized case, i.e., `to_primitive=1` and `no_idealize=1` at  https://atztogo.github.io/spglib/api.html#spg-standardize-cell.

Your script doesn't consider the transformation of the system. After applying the transformation, https://atztogo.github.io/spglib/definition.html#transformation-matrix-boldsymbol-p-and-origin-shift-boldsymbol-p , I think the order of atoms is correct. The `wrong` case, the transformation matrix is not unity, but 
```
-1 0 0
0 1 0
0 0 -1
```
I don't test that after applying this transformation (also should be done with origin shift), but probably this is the reason.

**Comment by noambernstein** [comment]
I hadn't thought about the transformation matrix.  You're right that we discussed that earlier, and I do use it in my full script, but I removed it (without thinking, I admit) in my simplified example in the mailing list. I don't understand how it would help this issue, though. The transformation matrix tells me how to go from the _standard_ lattice vectors to the symmetrized version of my real supercell vectors (plus a rotation), and I do use that to construct my symmetrized lattice vectors.  

However, I'm still a little confused by your comment, because I don't see how the transformation matrix can be related to the _primitive_ vectors.  The clearest example is something like passing a 2 atom diamond structure primitive cell (so the standard vectors are the 8 atom cube) to get_symmetry_dataset(), where you end up with half-integer values in the transformation matrix.  Applying that to the primitive cell vectors will give you something that's completely unrelated to any possible primitive, standard, or supercell vectors.

Basically, I don't see how it's possible to reliably use the current information in get_symmetry_dataset()["mapping_to_primitive"].   One possibility would be  a recipe for transforming the output of find_primitive() so that it is consistent with get_symmetry_dataset()["mapping_to_primitive"].  This seems to be what you're getting at in your last comment, but if you think this is possible (e.g. somehow using the transformation_matrix), I don't think I see how, so I'd like to request a more explicit formula.

I can also think of two other alternatives that would require extending spglib, or at least its python interface:
- get_symmetry_dataset() could return "mapping_to_std" that is consistent with the currently returned std_{positions,numbers}
- get_symmetry_dataset() could return primitive_{lattice,positions,numbers} that would be guaranteed to be consistent with the currently returned mapping_to_primitive

**Comment by atztogo** [comment]
If a crystal structure has a centring, as you wrote, the transformation matrix can be a non-integer matrix. However, further multiplying a known transformation matrix to its primitive cell basis vectors, the combined transformation matrix is always an integer matrix, which as I wrote above.

This is the point complicated. With `no_idealize=0`, this step is applied, however `no_idealize=1` not. I had to prepare two different versions of ways to create primitive cell and respective `mapping_to_primitive`. As written in documentation, `find_primitive` is just the alias of `no_idealize=0` and `to_primitive=1`. Therefore you don't need to use `mapping_to_primitive`. 

The procedure I wrote above gives you the symmetrized cell corresponding to your input cell. The order of atom indices can be changed, but the index mapping between the cells is (must be) a trivial task. However as I wrote, the order of atoms in their primitive cells are preserved algorithmically in the current code. I understand you are confused because it's confusing. The detailed algorithm is found here, https://arxiv.org/abs/1808.01590 . In fig. 1, the primitive cell obtained in `primitive cell search` section in the earlier steps is that with `no_idealize=1`. The standardized primitive cell is obtained after the last stop, whose detail is not described in this manuscript. The former primitive cell shape is not unique, but the later is unique up to generators of Euclidean normalizer (see international tables for crsytallography volume A) if the obtained space group is the same against tolerance value. The reason that makes confusing is in fact the tolerance, which makes spglib code so complicated, too. 

Finally your suggestion sounds good. But the first one is not possible when the input cell is a primitve cell having non-P centring, so a similar but different idea is necessary. The second is possible, but the shape can be different from that obtained from `find_primitive` that can make users confused again.

**Comment by atztogo** [comment]
Probably what you don't understand is the difference between the change of basis and rigid rotation. The transformation matrix is used for the former in my context, i.e., another basis vectors are described by linear combinations of basis vectors. In crystal, the choice is limited and cannot be continuous. The rigid rotation is the usual continuous one, https://en.wikipedia.org/wiki/Rigid_transformation. If you agree, I can draw some equations.

**Comment by noambernstein** [comment]
So I went back to the definition of the transformation matrix in https://atztogo.github.io/spglib/api.html#api-origin-shift-and-transformation to try to figure out what I'm missing, and either there's a bug or the documentation is confusing.  This very simple python script, which just multiplies the (column, to be consistent with the docs for the C API) standard lattice vectors on the right by the transformation matrix (i.e. exactly the first equation in the "Origin shift and lattice transformation" section) , gets a result which is _not_ the original cell.  That is inconsistent with what the documentation plainly states.  Am I misunderstanding something, or is there a bug?

```
tin 1052 : python check_transformation_matrix.py primitive_mapping_2.xyz
cell [[ 2.74964143e+00 -3.40081812e-25  3.11835576e-25]
 [ 1.45491188e-16  5.22864857e+00 -1.99574769e-23]
 [ 5.68612521e-25 -8.65007345e-24  3.01588863e+00]]
standard cell (column) vectors . transformation matrix
[[-2.74964143e+00 -1.45491188e-16  0.00000000e+00]
 [ 8.94396632e-49  5.22864857e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.01588863e+00]]
transformation matrix
[[-1.00000000e+00 -5.29127857e-17  0.00000000e+00]
 [ 1.71056941e-49  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00]]
```


[check_transformation_matrix.tar.gz](https://github.com/atztogo/spglib/files/2542850/check_transformation_matrix.tar.gz)

**Comment by noambernstein** [comment]
> If you agree this, I will start to draw some equations.
I do agree, yes - there's a transformation matrix (which, as returned by get_symmetry_dataset()) transforms from the standard cell lattice vectors to the input cell lattice vectors.  That transformation is discrete in a crystal, and must be consistent with its periodicity.  In addition there can also be a rigid rotation matrix, which is continuous and obeys the usual rotation matrix properties (doesn't change lengths or relative angles).

**Comment by atztogo** [comment]
As written here, https://atztogo.github.io/spglib/definition.html#def-idealize-cell, standardization can contain both the change of basis and rotation to make basis vectors be along specific Cartesian axes. In crystallography, usually we don't need this, but for the practical convenience, this operation, rigid rotation is included in the standardization in spglib. This is applied to find_primitive. Do you understand this? The transformation matrix returned in get_symmetry_dataset doesn't contain this rigid rotation, does only the change of basis.

**Comment by atztogo** [comment]
I know the documentation is confusing. But I don't know how I can make it better. If people have question, I want them to read through a book like this before discussion, https://onlinelibrary.wiley.com/doi/abs/10.1002/anie.201306902. Sometimes the reason their code doesn't work is not the matter of the code, but the insufficient understanding of convention and terminology of crystallography.

**Comment by atztogo** [comment]
For your `check_transformation_matrix.tar.gz`, as I wrote here,  https://atztogo.github.io/spglib/definition.html#def-idealize-cell, your crystal is rotated during the standardization. Please read this page very carefully. I feel I am losing my time for nothing.

**Comment by atztogo** [comment]
In addition, please read at least the section V of this manuscript https://arxiv.org/abs/1808.01590.

**Comment by atztogo** [comment]
I wrote two examples on this topic.
- https://atztogo.github.io/spglib/definition.html#example-crystallographic-choice-and-rigid-rotation
- https://atztogo.github.io/spglib/definition.html#example-transformation-to-a-primitive-cell

By the way, I don't see what is wrong in your last example, check_transformation_matrix.tar.gz. I thought it suffers from the rigid rotation, but I found it is not. I think you can recover the original basis vectors by (standardized ones * transformation matrix).

I don't see what makes you in trouble. I did my about the best and spent a lot of time for thinking about your problem and writing document. If you have not yet seriously read the crystallography books and our manuscript, please have time for reading. Please understand that this is not my job. I get nothing from maintaining and supporting spglib, purely volunteer. Please do your best if you want.

**Comment by noambernstein** [comment]
Clearly this discussion is becoming frustrating all around, so I want to start by saying that I'm very thankful that you've developed and released spglib, and I appreciate all the time you've put in to help me and the rest of the community.  I also want to assure you that I really do understand the difference, at least in principle, between the transformation matrix and a rotation matrix.  There may be some subtleties that I'm missing, but I really do understand the basic concept.  

First, let me respond to one thing you said in your previous response:

> By the way, I don't see what is wrong in your last example, check_transformation_matrix.tar.gz. I thought it suffers from the rigid rotation, but I found it is not. I think you can recover the original basis vectors by (standardized ones * transformation matrix).

Isn't this exactly what my script does?  
```
import spglib, ase.io, numpy as np
  
at = ase.io.read("primitive_mapping_2.xyz")
ds = spglib.get_symmetry_dataset(at,0.01)

print "cell", at.get_cell()
print "standard cell (column) vectors . transformation matrix\n", np.dot(ds["std_lattice"].T,ds["transformation_matrix"])
print "transformation matrix\n",ds["transformation_matrix"]
```

In the line `np.dot(ds["std_lattice"].T,ds["transformation_matrix"])` it is multiplying the standardized lattice vectors by the transformation matrix, right? The output I get is
```
cell [[ 2.74964143e+00 -3.40081812e-25  3.11835576e-25]
 [ 1.45491188e-16  5.22864857e+00 -1.99574769e-23]
 [ 5.68612521e-25 -8.65007345e-24  3.01588863e+00]]
standard cell (column) vectors . transformation matrix
[[-2.74964143e+00 -1.45491188e-16  0.00000000e+00]
 [ 8.94396632e-49  5.22864857e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.01588863e+00]]
```
As you can see in the output above,  this is _not_ equal to the original cell - it's off by a rotation (180 deg around the y axis,
```
-1 0 0
0 1 0
0 0 -1
```
), which is _not_ mentioned as a possibility in https://atztogo.github.io/spglib/api.html#api-origin-shift-and-transformation.  Do you get a different result?

Let's leave aside my original question (about the mapping to primitive cell) for now, until I read the things you mentioned.   My only questions for now are:

Q 1. Does my script implement the expression in the api-origin-shift-and-transformation page of the web site documentation `(a b c) = (a_s b_s c_s) P`?
Q 2a. If not, what is it doing wrong? There's only one substantive line, so it shouldn't be hard to locate an error
Q 2b. If it does implement the expression, then is the expression correct, or should it include a rotation, for example `(a b c) = R (a_s b_s c_s) P`

**Comment by atztogo** [comment]
I slept well last night. You are correct. I was wrong.
Q1. No.
Q2a. Your crystal is rigidly rotated 180degs around b-axis in the idealization.

In the spglib algorithm, before idealization, it doesn't consider about which geometric directions a, b, c axes should have in Cartesian coordinates, but only have relative relationships. Transformation matrix is made at this step. Please read the spglib manuscript to understand this.

Cmce has a symmetry operation corresponding to  -x,y+1/2,-z+1/2 (and also the one +origin shift). So Cmce, either if having 180degs rotation or not is almost randomly chosen (from user's point of view). Then by the idealization step (this is not written in manuscript, but in the web page), to align a, b, c to x, y, z Cartesian axes, 180 degs rotation is applied.

**Comment by noambernstein** [comment]
I'm disappointed that you feel this discussion was a waste of your time. I have put in considerable time into trying to understand the behavior by reading the documentation and source code, and I will read your updated documentation and follow up if I have any further thoughts.

**Comment by atztogo** [comment]
Clearly I don't have enough time to take care of spglib very much. Spglib doesn't make any money and any job for me. If I will not have a chance to have a job by losing my time for spglib (it can be soon), I will not be able to continue any support of spglib and many users will be disappointed. So it is relatively a small problem that I can disappoint you to save my time for me to survive to continue spglib support at the current level.

But often people understand my situation and ask questions or requests in mild ways. I know you try to make me understand your question, but you are a bit rushing. You want me to understand you in a way to beat me, which is what I feel. Of course you may not think that you are doing as what I feel, but I feel so and am tired. This asymmetry may come from our cultural difference where we grew up. But if you want to use spglib by fixing a possible bug or wrong documentation in spglib, you can be a bit more mild in discussion for me. You can also help me by pull requests.

**Comment by atztogo** [comment]
I will close this issue because of no response for long time. Please reopen this issue if you want to discuss more.

Now you have 'std_rotation_matrix' in the spglib dataset. If you want to idealize your crystal structure at the orientation of the original basis vectors choice, this will help.
