### ISSUE TITLE
Backwards-incompatible interface change caused by rename

### ISSUE THREAD

**Issue by merkys** [atztogo/spglib#73]
It seems that in version 1.12.0 all C library functions named `*_long_*` were renamed to `*_dense_*`. Such change is backwards-incompatible, as all code depending code had to be rewritten to use new names. My question is: was this a simple rename, or was the interface (parameter, return types) of these functions changed?

**Comment by atztogo** [comment]
It's a simple rename. I don't write any documentation about ``*_long_*`` or ``*_dense_*``, which implies it's under the development. So I expect nobody uses them.

**Comment by merkys** [comment]
Thanks for prompt reply. In C all non-`static` functions are public, that is, exposed and accessible by the users of a library. It is common practice to make all in-development things private.

I close the issue as I got the answer I was expecting.

**Comment by atztogo** [comment]
It is difficult to be very strict in C. All non-static functions in the other files are also public. If I make the function I want to test be static, it is not easy to test the function. A simple solution is that I ask people to understand my implicit message (please don't use the functions not explained in the documentation). Otherwise the development takes too much time and I can't continue to develop spglib by losing my job.

**Comment by merkys** [comment]
Understood. Just wanted to make sure what happened to the `*_long_*` functions. I've noticed this change while doing a strict interface check on Debian.

**Comment by atztogo** [comment]
I see. Does Debian check the name change of non-static functions in `*.h` files other than `spglib.h`? Unless so, why `spglib.h` is treated as exception?

**Comment by merkys** [comment]
AFAIK, Debian does a check on symbols in the shared library, as shown by `readelf --symbols libsymspg.so.1`.

**Comment by atztogo** [comment]
I see. Thanks for this information. I will remember this. I will notify you when I will change the name or type of non-static functions in `spglib.h` even if it is not documented.

**Comment by merkys** [comment]
Thanks. C library users would expect the `SONAME` change each time a backwards-incompatible change takes place in a library. In `CMakeLists.txt` the `SONAME` is controlled by `set(soserial "1")` (here `1` is the version of the library).

I see two possibilities how to appease the C library users in Debian and elsewhere:
1. to change the `soserial` to `2`, but you might want to reserve `2` for spglib v2 releases;
2. to make the old `*_long_*` functions accessible again by making them aliases of `*_dense_*`. If you would not want to have these aliases in spglib code here, I could place them in Debian version only.
