### ISSUE TITLE
clarify documentation of symprec?

### ISSUE THREAD

**Issue by ltalirz** [atztogo/spglib#74]
From the [documentation of `get_hall_number_from_symmetry`](https://atztogo.github.io/spglib/python-spglib.html#get-hall-number-from-symmetry) I understand that `symprec` is given in fractional coordinates.

I think it might make sense to mention is also [here](https://atztogo.github.io/spglib/python-spglib.html#symmetry-tolerance-symprec), where it currently says "Distance tolerance in Cartesian coordinates". 

Furthermore, I think it would be great if you could add [there](https://atztogo.github.io/spglib/python-spglib.html#symmetry-tolerance-symprec) one sentence of explanation on the meaning of `symprec` - something like
> For example, with symprec=0.01, deviations from exact symmetry are ignored as long as they do not exceed 1% of the length of the respective cell vector in any of the three dimensions 

if this is indeed what it means - I am not entirely sure ;-)

**Comment by atztogo** [comment]
Symmetry tolerance of `get_hall_number_from_symmetry` is an exception than most of the other API functions. As you pointed out, it is clearly confusing (and wrong) that the variable name `symprec` is used. At least the name should be changed.

I made `get_hall_number_from_symmetry` when I was requested by a user. It seems finally this user didn't use this feature. I don't use, too. Do you use this? If less users, I may remove this feature from API. I thought it's also a good idea to keep it if it is useful even if the number of users is small, but on one side, people request a strict API versioning (https://github.com/atztogo/spglib/issues/54 and https://github.com/atztogo/spglib/issues/73), which is painful for me though I want to do my best to respond. Now spglib is used very much in a way beyond my imagination and I am too busy to keep it maintained as good as people might expect.

**Comment by ltalirz** [comment]
@atztogo thanks for the quick reply!

> Do you use this? If less users, I may remove this feature from API. If less users, I may remove this feature from API. I thought it's also a good idea to keep it if it is useful even if the number of users is small

I don't use this function - as for the right balance between complexity and cleanliness of the API I'm afraid I can't provide much insight and must leave this decision to you.
If you decide you would like to eventually remove it, one way to do it would be to simply add a deprecation warning in the next release that says something like
> This function is scheduled to be removed by release x.y.z, use a combination of ... instead. If you need this function, please open an issue and explain why.

Irrespective of whether you keep the function or not, however, may I would suggest to:
 * please make it clear in the documentation that the meaning of this `symprec` is different from the regular one.
 * please still add one sentence [here](https://atztogo.github.io/spglib/python-spglib.html#symmetry-tolerance-symprec) explaining the meaning of the "regular" `symprec` - even if this may be obvious to you, it is not necessarily obvious to everyone.
I'm still confused - is it like this:
> For example, with symprec=0.01, deviations from exact symmetry are ignored as long as they do not exceed 0.01 along x, y or z in the length units of the atomic structure provided.

Because I still see mentions of fractional coordinates [elsewhere in the code](https://github.com/atztogo/spglib/blob/e10a8f24e6e3bc1adfd8c511073442c0e7fc67b6/src/spglib.h#L81)

**Comment by atztogo** [comment]
Thanks for your comment. After some thought during my jogging, I think experimental public functions are better to be sent to non-official location like `spglib_exp.h`. This I would like to discuss with @merkys and @jochym. 

`symprec` is a difficult  parameter. It is not straightforward to explain. Strictness is sacrificed for the usability. Normally `symprec` is used to judge if two position vectors x and x' in cartesian coordinates are at the same point by `|x' - x| < symprec`. The detail is written in https://arxiv.org/abs/1808.01590. So for more detail, it may be better to provide a link to this manuscript from the spglib documentation.

**Comment by ltalirz** [comment]
Thanks for the clarification!

I would suggest to add the "rough" explanation in the docs + a link to the arxiv manuscript
>  Roughly speaking, two position vectors `x` and `x'` in cartesian coordinates are considered to be the same if `|x' - x| < symprec`. For more details, see the [spglib paper](https://arxiv.org/abs/1808.01590), equation x.

**Comment by atztogo** [comment]
It took very long time until I update the documentation. Following your advise, I did this job. Thanks for your comments.

https://atztogo.github.io/spglib/python-spglib.html#symmetry-tolerance-symprec
https://atztogo.github.io/spglib/variable.html#variables-symprec

**Comment by ltalirz** [comment]
Thanks a lot @atztogo !
And no worries, I also just started yesterday finding the time for going through the issues that came up during the tutorial.

Notifying @danieleongari

**Comment by sgbaird** [comment]
Even if the following statement from @ltalirz 's original post may not be exactly correct:

> For example, with symprec=0.01, deviations from exact symmetry are ignored as long as they do not exceed 1% of the length of the respective cell vector in any of the three dimensions

it seems like it's still a tolerance relative to the dimensions of the unit cell (i.e. symprec doesn't have units of e.g. Angstroms). Is that correct?

![image](https://user-images.githubusercontent.com/45469701/173170589-65ba6eed-e439-48c4-ba77-8177dd081fa6.png)

**Comment by sgbaird** [comment]
forgot to ping @atztogo

**Comment by atztogo** [comment]
For `get_hall_number_from_symmetry`, yes. I should have designed its API with `(a, b, c)`.

**Comment by sgbaird** [comment]
@atztogo ok, thanks! What about for the rest of the API? Specifically https://spglib.github.io/spglib/variable.html#symprec. Is it relative or is it absolute (angstroms)?

**Comment by atztogo** [comment]
It is Cartesian. The distance unit is the same as the user's input of `(a, b, c)`.

**Comment by sgbaird** [comment]
Thank you!
