### ISSUE TITLE
test_change_of_basis broken on macos/python 2.7?

### ISSUE THREAD

**Issue by risicle** [atztogo/spglib#78]
Hi,

With `spglib` 0.12.2.post0, specifically on the combination of macos & python 2.7 I'm getting 

```
test_change_of_basis (test_change_of_basis.TestChangeOfBasis) ... Assertion failed: (n != len_list), function py_get_dataset, file _spglib.c, line 394.
```

This is with numpy 1.16.3. Other python versions on macos and python 2.7 on linux work fine - it's just this particular combination. Can anyone reproduce this?

**Comment by atztogo** [comment]
I think it's weird because your assertion error occurred in _spglib.c. You can count number of `n++` by your eye and if it is 19, then I don't see what happened for you.

**Comment by risicle** [comment]
Um... I might be going mad but looking at that file @ tag 1.12.2, I count 19 unconditional `n++`s. How can code ever pass that assertion?

Unless your `assert()` is getting compiled as a no-op in the vast majority of cases except this one...?

**Comment by atztogo** [comment]
You are correct. I was wrong.

When compiling spglib CAPI, as default `-DNDEBUG` is set, this deactivates `assert` in my environment. This may happen most of the systems, but probably not your case.

I fixed assert line replacing `!=` by `==`. Then I modified `setup.py` in a dirty way (so I'm not sure if it works for every system) to activate the assertion when running `python setup.py test`. I referred [this page](https://stackoverflow.com/questions/24275714/how-to-override-dndebug-compile-flag-when-building-cython-module). See https://github.com/atztogo/spglib/commit/d57070831585a6f02dec0a31d25b375ba347798c.

Thank you for telling me this.

**Comment by atztogo** [comment]
Probably this was fixed. So I will close this issue. If needed, please reopen this issue.

**Comment by nanoflow** [comment]
Hi, I just had the same problem on a fresh Ubuntu (the standard one from the Windows Hyper-V Ubuntu 18.04.3 LTS). I installed phonopy by cloning from github. Changing line 394 in _spglib.c and rerunning setup.py worked fine for me. Does anything speak against changing that in the source files?

**Comment by atztogo** [comment]
I think this is already fixed at https://github.com/atztogo/spglib/commit/d57070831585a6f02dec0a31d25b375ba347798c.
