### ISSUE TITLE
Inconsistent Hall number detection

### ISSUE THREAD

**Issue by aoterodelaroza** [atztogo/spglib#80]
Hi again! I think I found a problem with the routines that detect the Hall number from the symmetry operations. They seem to work just fine so long as the setting is the standard for the space group in question. For instance, space group 9 (Cc, monoclinic) corresponds to Hall numbers 39 to 56. C1c1 is the default (hall = 39) but there is also A1n1 (40), etc. It seems that if I feed the symmetry operations of any of these setings to `get_hall_number_from_symmetry`, it always returns the default setting number (39) instead of the correct number:
~~~
for i in range(39,57):
    sym = get_symmetry_from_database(i)
    print(i,get_hall_number_from_symmetry(sym['rotations'],sym['translations']))
~~~
results in:
~~~
(39, 39L)
(40, 39L)
(41, 39L)
(42, 39L)
(43, 39L)
(44, 39L)
(45, 39L)
(46, 39L)
(47, 39L)
(48, 39L)
(49, 39L)
(50, 39L)
(51, 39L)
(52, 39L)
(53, 39L)
(54, 39L)
(55, 39L)
(56, 39L)
~~~
Am I missing something here? The rotation and translation operations for the non-standard ITA settings are correct, but it seems that the Hall number detection is off.

**Comment by atztogo** [comment]
Spglib algorithm has no ability to differentiate Hall symbol against input crystal structure of a set of symmetry operations. Therefore, what you found is what implemented. But it is true that the method name is not intuitive. One note I want to leave here is that space group is a group, so all Hall symbols belonging to one space group type have the same group.

**Comment by aoterodelaroza** [comment]
Sounds good! Sorry for the confusion. Thanks!
