### ISSUE TITLE
inconsistency in get_spacegroup_type output

### ISSUE THREAD

**Issue by pteronura** [atztogo/spglib#81]
It appears that the values for 'pointgroup_international' and 'pointgroup_schoenflies' are swapped in the output.
Example (spglib==1.14.1.post0):
In [1411]: pprint(spglib.get_spacegroup_type(436))
{'arithmetic_crystal_class_number': 41L,
 'arithmetic_crystal_class_symbol': u'-3R',
 'choice': u'H',
 'hall_symbol': u'-R 3',
 'international': u'R -3',
 'international_full': u'R -3',
 'international_short': u'R-3',
 'number': 148L,
 'pointgroup_international': u'C3i',
 'pointgroup_schoenflies': u'-3',
 'schoenflies': u'C3i^2'}

**Comment by atztogo** [comment]
Good catch! Thanks. Fixed on develop branch.

**Comment by atztogo** [comment]
I close this issue because it was done.
