### ISSUE TITLE
Please use GNUInstallDirs.cmake

### ISSUE THREAD

**Issue by StefanBruens** [atztogo/spglib#83]
Some distributions use e.g  /usr/lib64/ on 64bit archs

https://cmake.org/cmake/help/v3.4/module/GNUInstallDirs.html

`DESTINATION` should then be
- `CMAKE_INSTALL_LIBDIR` for libraries
- `CMAKE_INSTALL_INCLUDEDIR` for the header(s)

**Comment by atztogo** [comment]
Thanks for your advise. Could you send PR?

**Comment by atztogo** [comment]
I close this because fixed.
