### ISSUE TITLE
Irreducible k-points in BZ not consistent with VASP

### ISSUE THREAD

**Issue by QijingZheng** [atztogo/spglib#88]
Hi 

I have a cell 
```
(array([[ 3.2091118 , -0.        , -0.        ],
        [-1.6045559 ,  2.77917234, -0.        ],
        [ 0.        , -0.        , 12.08110594]]),
 array([[0.666667  , 0.333333  , 0.32219129],
        [0.333333  , 0.666667  , 0.82219111],
        [1.        , 1.        , 0.19265161],
        [0.333333  , 0.666667  , 0.45196541],
        [0.        , 0.        , 0.69264784],
        [0.666667  , 0.333333  , 0.95196895]]),
 array([42, 42, 16, 16, 16, 16]))
```
when doing  ir_reciprocal_mesh with mesh size [7, 7, 3], spglib gives me 20 ir k-points while vasp (vasp.5.4.4.18Apr17-6-g9f103f2a35) only gives me 16.

```
mapping, grid = spglib.get_ir_reciprocal_mesh(mesh, cell, is_shift=[0, 0, 0])
spg_ir_kpath = (grid[np.unique(mapping)] / np.array(mesh, dtype=float)) 
```

![scrot_kaka](https://user-images.githubusercontent.com/8523070/75316861-71c5f880-58a1-11ea-8664-af0da7eb24e6.png)

The left part in the above figure is ir_kpoints generated by spglib, the right panel by vasp.

I noticed that there is a similar closed issue, however, the lattice of my case is different.

Best
Qijing

**Comment by atztogo** [comment]
Which is correct?

**Comment by QijingZheng** [comment]
The BZ of my cell look like:

![Brillouin_zone_in_hexagonal_lattice](https://user-images.githubusercontent.com/8523070/75334724-4eac4080-58c3-11ea-955c-f5213d8277f7.png)

If you check the ir k-points of vasp, you can see that there are both 8 ir k-points in kz = 0.0 plane and kz = 1/3 plane, which make sense since the two planes are parallel. However, the number of ir k-points from spglib in the kz = 1/3 plane is 12, more than that of kz = 0 plane.

Therefore, I believe that there might something wrong with spglib.

**Comment by atztogo** [comment]
How about `mapping, grid = spglib.get_ir_reciprocal_mesh(mesh, cell, is_shift=[0, 0, 0], symprec=1e-4)`?

**Comment by QijingZheng** [comment]
Reducing the `symprec` to `1e-4` solves the problem. Thank you!

**Comment by QijingZheng** [comment]
I will close the issue.

**Comment by atztogo** [comment]
spglib uses distance measure in Cartesian coordinates, but VASP in fractional coordinates.
