### ISSUE TITLE
Problem with equivalent atoms

### ISSUE THREAD

**Issue by lauri-codes** [atztogo/spglib#90]
First, thank you for creating this superb library! I have used it quite a lot and it has worked wonders.

Just recently I noticed that there was an inconsistency with `equivalent_atoms` that I could not figure out. It may be entirely due to me not understanding what is going on but I hope you could shed a light on what is happening.

When running the following code

```python
import spglib

positions = [
    [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],                                                                                    
    [5.00000783e-01, 5.00000105e-01, 5.00000504e-01],
    [2.57675031e-01, 2.57675031e-01, 0.00000000e+00],
    [7.42324606e-01, 7.42324606e-01, 0.00000000e+00],
    [7.42441461e-01, 2.57559427e-01, 4.18791129e-02],
    [4.57816602e-01, 5.42184286e-01, 2.42498450e-01],
    [4.13846169e-02, 9.58616271e-01, 2.57474206e-01],
    [7.57373910e-01, 2.42626978e-01, 4.58800327e-01],
    [2.42314486e-01, 2.42313809e-01, 5.00000504e-01],
    [7.57685827e-01, 7.57685150e-01, 5.00000504e-01],
    [2.42627655e-01, 7.57373233e-01, 5.41200681e-01],
    [9.58616953e-01, 4.13839350e-02, 7.42525529e-01],
    [5.42183696e-01, 4.57817192e-01, 7.57501282e-01],
    [2.57560109e-01, 7.42440779e-01, 9.58120623e-01],
    [9.99745256e-01, 5.00077432e-01, 2.50229920e-01],
    [4.99921738e-01, 2.53959000e-04, 2.50230128e-01],
    [5.00078114e-01, 9.99744574e-01, 7.49769816e-01],
    [2.54636000e-04, 4.99921061e-01, 7.49770880e-01],
    [5.00000444e-01, 5.00000444e-01, 0.00000000e+00],
    [3.38500000e-07, 9.99999661e-01, 5.00000504e-01],
]
numbers = [28, 28, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 38, 38, 38, 38, 52, 52]
lattice = [
    [-3.93057, -3.994236, -0.010812],
    [3.93057, -3.994236, 0.010812],
    [-0.030735, 0.0, 7.861732]
]
cell = (lattice, positions, numbers)

# Get symmetry dataset
symmetry_dataset = spglib.get_symmetry_dataset(cell, symprec=0.01)

# Print site information for each atom
spg = symmetry_dataset["number"]
wyckoff_letters = symmetry_dataset["wyckoffs"]
equivalent_atoms = symmetry_dataset["equivalent_atoms"]
site_symmetry_symbols = symmetry_dataset["site_symmetry_symbols"]
print("Belongs to space group: {}".format(spg))
for w, e, s in zip(wyckoff_letters, equivalent_atoms, site_symmetry_symbols):
    print(w, e, s)
```

I get the following output on my machine (Ubuntu 18.04, spglib 1.14.1.post0) :

```
Belongs to space group: 87                                                                                                         
a 0 4/m..
a 0 4/m..
e 2 4..
e 2 4..
h 4 m..
h 5 m..
h 5 m..
h 4 m..
e 2 4..
e 2 4..
h 4 m..
h 5 m..
h 5 m..
h 4 m..
d 14 -4..
d 14 -4..
d 14 -4..
d 14 -4..
b 18 4/m..
b 18 4/m..
```
From what I understand, for the standard cell of space group 87, the Wyckoff site h should have multiplicity of 8. In the output, there are correctly 8 atoms reported with letter h, but for some reason, these 8 atoms do not have the same number in the column for `equivalent_atoms`. Instead, they are split so that half have the number 4 and the other half have the number 5. Is this intentional and if so what is the reasoning behind this? My use case is that I would like to group the atoms into "Wyckoff sets" ([as seen here](https://www.cryst.ehu.es/cgi-bin/cryst/programs/nph-normsets?from=wycksets&gnum=87)) by using the numbers in `equivalent_atoms` for doing the grouping.

Tell me if anything is unclear and you need more details.

**Comment by atztogo** [comment]
Thanks for your report. I agree. This is strange. I will have a look into.

**Comment by atztogo** [comment]
I see. Probably this result is on purpose. In spglib, symmetry operations are found to respect the point group of your lattice made of your input basis vectors. But the space group type and Wyckoff letters are given for the space group type found for the primitive cell. But the equivalent atoms information is given for the symmetry operations.

This is made for the practical purpose, but not at all crystallographic.

You can see the number of symmetry operations found is different between before and after standardization although the number of atoms is kept. This is due to broken symmetry. I wrote this in the manuscript spglib (https://arxiv.org/abs/1808.01590) at my hand. I should update the arxiv manuscript. If you want (and if I could know your mail address), I will give you my manuscript.

```python
import spglib


def print_syminfo(cell):
    # # Get symmetry dataset
    symmetry_dataset = spglib.get_symmetry_dataset(cell, symprec=1e-1)

    # Print site information for each atom
    spg = symmetry_dataset["number"]
    wyckoff_letters = symmetry_dataset["wyckoffs"]
    equivalent_atoms = symmetry_dataset["equivalent_atoms"]
    site_symmetry_symbols = symmetry_dataset["site_symmetry_symbols"]
    print("Belongs to space group: {}".format(spg))
    for w, e, s in zip(wyckoff_letters, equivalent_atoms, site_symmetry_symbols):
        print(w, e, s)

    std_cell = (symmetry_dataset['std_lattice'],
                symmetry_dataset['std_positions'],
                symmetry_dataset['std_types'])

    print("Number of symmetry operations: %d"
          % len(symmetry_dataset['rotations']))

    return std_cell


def main():
    positions = [
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [5.00000783e-01, 5.00000105e-01, 5.00000504e-01],
        [2.57675031e-01, 2.57675031e-01, 0.00000000e+00],
        [7.42324606e-01, 7.42324606e-01, 0.00000000e+00],
        [7.42441461e-01, 2.57559427e-01, 4.18791129e-02],
        [4.57816602e-01, 5.42184286e-01, 2.42498450e-01],
        [4.13846169e-02, 9.58616271e-01, 2.57474206e-01],
        [7.57373910e-01, 2.42626978e-01, 4.58800327e-01],
        [2.42314486e-01, 2.42313809e-01, 5.00000504e-01],
        [7.57685827e-01, 7.57685150e-01, 5.00000504e-01],
        [2.42627655e-01, 7.57373233e-01, 5.41200681e-01],
        [9.58616953e-01, 4.13839350e-02, 7.42525529e-01],
        [5.42183696e-01, 4.57817192e-01, 7.57501282e-01],
        [2.57560109e-01, 7.42440779e-01, 9.58120623e-01],
        [9.99745256e-01, 5.00077432e-01, 2.50229920e-01],
        [4.99921738e-01, 2.53959000e-04, 2.50230128e-01],
        [5.00078114e-01, 9.99744574e-01, 7.49769816e-01],
        [2.54636000e-04, 4.99921061e-01, 7.49770880e-01],
        [5.00000444e-01, 5.00000444e-01, 0.00000000e+00],
        [3.38500000e-07, 9.99999661e-01, 5.00000504e-01],
    ]
    numbers = [28, 28, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 38, 38, 38, 38, 52, 52]
    lattice = [
        [-3.93057, -3.994236, -0.010812],
        [3.93057, -3.994236, 0.010812],
        [-0.030735, 0.0, 7.861732]
    ]
    cell = (lattice, positions, numbers)

    print("Before standardization")
    print("----------------------")
    std_cell = print_syminfo(cell)
    print("")

    print("After standardization")
    print("----------------------")
    print_syminfo(std_cell)


main()
```
This gives,
```
Before standardization
----------------------
Belongs to space group: 87
a 0 4/m..
a 0 4/m..
e 2 4..
e 2 4..
h 4 m..
h 5 m..
h 5 m..
h 4 m..
e 2 4..
e 2 4..
h 4 m..
h 5 m..
h 5 m..
h 4 m..
d 14 -4..
d 14 -4..
d 14 -4..
d 14 -4..
b 18 4/m..
b 18 4/m..
Number of symmetry operations: 8

After standardization
----------------------
Belongs to space group: 87
a 0 4/m..
e 1 4..
e 1 4..
h 3 m..
h 3 m..
h 3 m..
h 3 m..
d 7 -4..
d 7 -4..
b 9 4/m..
a 0 4/m..
e 1 4..
e 1 4..
h 3 m..
h 3 m..
h 3 m..
h 3 m..
d 7 -4..
d 7 -4..
b 9 4/m..
Number of symmetry operations: 16
```

**Comment by lauri-codes** [comment]
Ok, I think I understand now.

So yes, one option is to run the symmetry analysis on the already standardized cell to get the correct information. In my case, I would, however, be running the symmetry analysis for many structures (millions). Although spglib is fast, symmetry detection is a kind of a bottleneck for me. Thus I would really want to avoid running `spglib.get_symmetry_dataset` twice.

Do you think there is a faster alternative way to get the equivalent atoms in the standardized cell? I would be interested in the updated manuscript, my email is lauri.himanen@gmail.com.

**Comment by lauri-codes** [comment]
After looking at the manuscript, I think equivalent atoms in the standardized cell can be quickly identified in the step where the Wyckoff letters are identified (Sec. VI B in the manuscript.). Unless you are very eager to work on this addition, I will myself at some point look at the source code to see If I could figure out how to do it quickly.

Thanks a lot for your time!

**Comment by atztogo** [comment]
Yes, I was writing it. It is exactly here, https://github.com/atztogo/spglib/blob/18b4db4b02753fbff7358af217e70acce0783e10/src/refinement.c#L386.
The following is what I was writing.

I think there is no good way currently to suffice your request. Internally spglib code, it's easily done. So extracting it to the dataset is a possible way, which needs modification of spglib of course.

Spglib aims robustness and easy maintenance for me than computational performance. So I don't run profiling at all. Some tunings were done previously by @ExpHP, which made a lot of speed up for large unit cell (one order smaller complexity was achieved).

Spglib is written to be thread safe except for error message functions (spg_get_error_code and spg_get_error_message). So writing a wrapper to run in multithread may give you better performance per machine, if you have not yet done it (I've never tried this.)

**Comment by lauri-codes** [comment]
Hi @atztogo!

I made of fork of your repository in which the equivalent atoms for the standardized cell are now reported in the symmetry dataset under key "std_equivalent_atoms". As you said it was not a big change. I was careful in the memory management and at least for my test structures, it works fine. My change simply keeps the already calculated equivalent atoms for the bravais cell (done in function `get_Wyckoff_positions`) and carries them all the way to the symmetry dataset that is created in `get_dataset`. Also the python interface is modified to expose them as keys in the dictionary returned by `get_symmetry_dataset`.

Do you think it would be possible to merge my fork to your master branch? You can, of course, review the code and we can discuss the changes.

**Comment by atztogo** [comment]
I agree to include your change (I've not watched your code yet). But we have to be careful to the name.

We have to keep backward compatibility during v1.x, so let's not change the current existing ones. We can change all of them if needed when we release v2.0 following semantic versioning.

Clearly `std_equivalent_atoms` is wrong. `std_*` are for the new crystal structure that is standardized, but `wyckoffs` is for the atoms of the input crystal structure. What you implemented can contain the equivalent information to crystallographic orbits (https://dictionary.iucr.org/Crystallographic_orbit) though it is not very correct. It may be misleading but it can be supported by documentation. Simply `crystallographic_orbits` may be tentatively acceptable, I think. At v2.0, we should consider carefully the namings.

**Comment by lauri-codes** [comment]
Great! I agree with your suggestion for the name. I have now made a new pull request where the data is provided under `crystallographic_orbits`. Please check when you have time and modify as you see fit.
